#!/bin/bash
#generate network configs 

if [ "$nw_mode" = "Static" ]
then

mv /etc/network/interfaces /etc/network/interfaces.bak
cat > /etc/network/interfaces <<interfaces
##interface generated by kodi-install-script!

auto lo
iface lo inet loopback

###$nw_iface IPv4 static configuration
auto $nw_iface

iface $nw_iface inet static	
	address $nw_ip
	netmask $nw_netmask
	gateway $nw_gateway
	dns-nameservers $nw_dns1 $nw_dns2
interfaces

fi
