#!/bin/bash
#generate network configs 

if [ "$nw_mode" = "Static" ]
then
	mv /etc/network/interfaces /etc/network/interfaces.bak

if [ "$nw_use_wifi" = "false" ]
then
cat > /etc/network/interfaces <<interfaces
##interface generated by kodi-install-script!

auto lo
iface lo inet loopback

###$nw_iface IPv4 static configuration
auto $nw_iface

iface $nw_iface inet static	
	address $nw_ip
	netmask $nw_netmask
	gateway $nw_gateway
	dns-nameservers $nw_dns1 $nw_dns2
interfaces

fi

else
#create wpasupplicant.conf
cat > /etc/wpa_supplicant/wpa_supplicant.conf <<wpasupplicantconf
###the base config, do not modify!

ctrl_interface=/var/run/wpa_supplicant
eapol_version=1
ap_scan=1

#ap specific config
wpasupplicantconf

echo "wpa_passphrase $nw_wifi_ssid $nw_wifi_psk" >> /etc/wpa_supplicant/wpa_supplicant.conf
cat > /etc/network/interfaces <<interfaces
##interface generated by kodi-install-script!

auto lo
iface lo inet loopback

###$nw_iface IPv4 static configuration
auto $nw_iface

iface $nw_iface inet static	
	address $nw_ip
	netmask $nw_netmask
	gateway $nw_gateway
	dns-nameservers $nw_dns1 $nw_dns2
	wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
interfaces
fi
